version: '3.8'
services:
  speakx-flask-api:
    image: 153518899895.dkr.ecr.us-east-1.amazonaws.com/speakx-ecr:latest
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/nginx/speakx-flask.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/flightman.lol:/etc/nginx/certs:ro
      - /etc/letsencrypt/archive/flightman.lol:/etc/nginx/archive:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem:ro