version: '3.8'
services:
  speakx-flask-api:
    image: 153518899895.dkr.ecr.us-east-1.amazonaws.com/speakx-ecr:latest
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Bind mount the entire letsencrypt directory
      - /etc/letsencrypt:/etc/letsencrypt:ro
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf

configs:
  nginx_config:
    content: |
      server {
        listen 443 ssl;
        server_name flightman.lol;

        ssl_certificate /etc/letsencrypt/live/flightman.lol/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/flightman.lol/privkey.pem;

        location / {
          proxy_pass http://speakx-flask-api:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }

      server {
        listen 80;
        server_name flightman.lol;
        return 301 https://$server_name$request_uri;
      }