version: '3.8'
services:
  speakx-flask-api:
    image: 153518899895.dkr.ecr.us-east-1.amazonaws.com/speakx-ecr
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/nginx/speakx-flask.conf:/etc/nginx/conf.d/default.conf
      - ./app/cert.pem:/etc/nginx/cert.pem
      - ./app/key.pem:/etc/nginx/key.pem