version: '3.8'
services:
  speakx-flask-api:
    image: 153518899895.dkr.ecr.us-east-1.amazonaws.com/speakx-ecr:latest
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/flightman.lol/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/flightman.lol/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./app/nginx/speakx-flask.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
    command: /bin/sh -c "mkdir -p /etc/nginx/certs && exec nginx -g 'daemon off;'"