version: '3.8'
services:
  flask-app:
    image: your-ecr-repo/speakx-flask-app:latest
    ports:
      - "3000:3000"
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config: