version: '3.8'

services:
  flask-app:
    image: 153518899895.dkr.ecr.us-east-1.amazonaws.com/speakx-ecr  
    ports:
      - "3000:3000"  # Flask app port

  caddy:
    image: caddy:latest
    ports:
      - "443:443"    # HTTPS
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile  
      - caddy_data:/data                        
      - caddy_config:/config                    

volumes:
  caddy_data:
  caddy_config: