name: Deploy to AWS
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/speakx-ecr:latest
          
          echo "Building Docker image..."
          docker build -t $IMAGE_URI .

          echo "Pushing Docker image to ECR..."
          docker push $IMAGE_URI

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Navigating to deployment directory..."
            cd speakx-devops || exit

            echo "Stopping running containers..."
            docker rm -f $(docker ps -q) || true

            echo "Pulling updated Docker images..."
            docker-compose pull

            echo "Starting updated services..."
            docker-compose up -d
